### PR TITLE
netaddr: add IPv4Zero

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

I need this for work, and it has symmetry with net.IPv4zero and netaddr.IPv6Unspecified.

### CODE REVIEW

**Comment by bradfitz** [comment]
Not a huge fan, as `netaddr.IPv4(0, 0, 0, 0)` is more explicit and shorter than `netaddr.IPv6Unspecified()` too. (https://play.golang.org/p/1jCC_et5dRU)

**Comment by bradfitz** [comment]
Also, `IPv4Zero` sounds like `IP.IsZero`. Shouldn't it be `IPv4Unspecified` to match?

**Comment by mdlayher** [comment]
No strong feelings here. I went with the name the stdlib uses but could also just do an inline zero address as you mention.

**Comment by bradfitz** [comment]
Oh, hah, I didn't even know `net` had that. But it also has both:

```
    IPv6zero                   = IP{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    IPv6unspecified            = IP{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
```

**Comment by bradfitz** [comment]
Sounds like maybe we don't need this now, with IP.IsUnspecified?

**Comment by mdlayher** [comment]
AFK for a bit so I forget exactly, but I think I don't need it. We do still have IPv6Unspecified. Should we remove that one for the same reason?

**Comment by bradfitz** [comment]
IPv6Unspecified is a bit harder to type by hand, though.

**Comment by mdlayher** [comment]
Nope, don't need this anymore. I do use IPv6Unspecified a lot in tests. Will close.

**Pull request closed without merging**
