### PR TITLE
netaddr: add initial well-known IP addresses

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

These are the only two "constants" I need at the moment. The standard library exposes a few more.

It'd be nice if these could be immutable but I think this is probably reasonable.

### CODE REVIEW

**Comment by bradfitz** [comment]
It'd be ideal if we could do this without init work. And something the linker could discard.

**Comment by mdlayher** [comment]
Yeah. I am curious if there is something more clever that could be done, but I also know that being able to check equality via `==` was an explicit goal with this type.

Here's a thought that comes to mind:

```go
type WellKnown int

const (
    Unspecified WellKnown = iota
    IPv6LinkLocalAllNodes
)

func (ip IP) Is(known WellKnown) bool {}

// Usage:
ip, _ := netaddr.ParseIP("::")
fmt.Println(ip.Is(netaddr.Unspecified))
// true
```

**Comment by bradfitz** [comment]
No, I was thinking just laying out the value in memory to help the linker (see https://github.com/golang/go/issues/19533 and https://github.com/golang/go/issues/38450#issuecomment-614248472). Not a new type or API.

Something like:

```go
var ip6Unspecified = IP{v6Addr{}}
func IPv6Unspecified() IP { return ip6Unspecified }
```

Then:

* linker can discard it all (confirm that the unexported var can be discard to and doesn't make an init func?)
* it doesn't allocate at runtuime
* no new types
* people can't modify exported package vars

**Comment by mdlayher** [comment]
I see! I'm good with that.

**Comment by mdlayher** [comment]
Updated.

**Comment by mdlayher** [comment]
Any more thoughts? Thanks!

**Comment by mdlayher** [comment]
I'll take that as my "+2", but feel free to chime in or open issues/PRs if something's amiss! Thanks.

**Pull request merged**
