### PR TITLE
use intern.GetByString in IP.WithZone

### PR DESCRIPTION
**Pull request by josharian**
Removes the remaining allocation from IPv6 IP parsing.

### CODE REVIEW

**Comment by bradfitz** [comment]
LGTM. Add allocation test?

**Comment by josharian** [comment]
Will do next year. :)

**Comment by bradfitz** [comment]
> Will do next year. :)


86a1d3ac8c142b544ef13ef0636eb80ff433dcec

**Comment by josharian** [comment]
Thanks!

**Pull request merged**
