### PR TITLE
More 4to6 test cases

### PR DESCRIPTION
**Pull request by andrewlouis93**
Came here from https://github.com/golang/go/issues/37921 :) 

Just a small PR adding some more test coverage here.

### CODE REVIEW

**Comment by andrewlouis93** [comment]
cc @bradfitz

**Comment by bradfitz** [comment]
Sorry, I saw this when it came in but then got distracted going to update Go's docs to mention that Go even supports parsing that IPv4-in-IPv6 string form:

https://github.com/golang/go/commit/2bed279721d684de828d0027db43a9d6283938a1

**Comment by andrewlouis93** [comment]
No worries! Thanks for updating the comment as well :)

**Comment by andrewlouis93** [comment]
Let me know if there are issues you need picking up here, would love to help contribute here @bradfitz

**Pull request merged**
