### PR TITLE
netaddr: add MustParse* helpers

### PR DESCRIPTION
**Pull request by josharian**
Several Tailscale packages each have their own copy of these helpers.

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]
I'm lukewarm on this. I guess regexp and template have them. They seem to invite misuse but whatever. They're named scarily and conventionally at least. 

How do others feel?

**Review by mdlayher — APPROVED** [review]
I add these in my test files all the time, so I'd be +1.

**Comment by danderson** [comment]
I've written these so many times, I really want them somewhere, if not here then in a tailscale util package.

Misuse is a possibility, but the Must* convention is well understood in Go, so you get what you pay for.

Minor bikeshed: `MustIP` and `MustIPPrefix` ? That's what I all these in test code.

**Comment by bradfitz** [comment]
Let's not try to shorten them. Test code likely will do that anyway to remove the "netaddr." prefix anyway.

**Comment by danderson** [comment]
Fair 'nuf.

**Comment by josharian** [comment]
Sounds like consensus enough. Merging.

**Pull request merged**
