### PR TITLE
netaddr: change uint128.commonPrefixLen receiver name for consistency

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

### CODE REVIEW

**Comment by josharian** [comment]
I weakly prefer a/b to consistent receivers. Leaving for others.

**Comment by mdlayher** [comment]
I see now, it didn't even occur to me that this was intentional. I just assumed it was an oversight. I feel less strongly now as well.

**Comment by josharian** [comment]
Could do u/v or u/t?

**Comment by mdlayher** [comment]
I like u/v. Done.

**Review by josharian — APPROVED** [review]

**Pull request merged**
