### PR TITLE
add IPPrefix.IsSingleIP

### PR DESCRIPTION
**Pull request by josharian**
I just encountered the second place where this was implemented in Tailscale, each different ways.

### CODE REVIEW

**Review by mdlayher — APPROVED** [review]
LGTM. This is something I've rolled by hand as well.

**Review by bradfitz — COMMENTED** [review]
Lgtm

**Comment by danderson** [comment]
Once again I wish Go had uint128, because Prefix could really use a Size() as well, which would subsume this. But being unable to represent 2^128 sanely, this LGTM.

**Comment by josharian** [comment]
Please add a short note to https://github.com/golang/go/issues/9455. Use cases like this can help drive such proposals forward. I want uint128 too.

**Pull request merged**
